### ISSUE TITLE
Nothing works....

### ISSUE THREAD

**Issue by KadePcGames** [Cvolton/GMDprivateServer#116]
I did it all replaced everything i can make a account i can login in to it and when i set my id to 71 and it gives me robtops account comments. I cant download levels. Whitch is i can upload them but i cant play them

**Comment by DEXUSGAMER** [comment]
Hello KadePcGames!,

I know that error, but, please help me giving to me the 2.11 private server files please, i will help u, add me on whatsapp: +56940448342

because i don't find any 2.11 files but i know how to make it

or message me on discord: mikepro0998#8445

**Comment by AnubisTDG** [comment]
Guys I'm pretty sure that the server is still being updated for 2.11 compatibility. Hopefully it'll be out soon but until then I would recommend that you just use 2.1 for now. As for the problem above, did you replace the base64 code as well? Because RobTop tried to prevent private servers by using base64 for the server links.

**Comment by Cvolton** [comment]
issue solved in Discord DMs, the EXE wasn't hex-edited properly
