### ISSUE TITLE
What are all commands?

### ISSUE THREAD

**Issue by UpriseDragon** [Cvolton/GMDprivateServer#159]
Title says all

**Comment by AnubisTDG** [comment]
Here is the list of commands from what I know.

!rate (NA,Easy,Normal,Hard,Harder,Insane,Demon) (amount of stars) - rates the level

!feature - features the level

!epic - epic features the level

!unepic - removes epic feature from the level

!setacc (account name) - sets the account 

!verifycoins - verifies the coins in the level, making them silver instead of bronze.

!daily - Sets the level as daily [might not work right away]

!weekly - Sets the level as weekly demon

!delet - Deletes the level from the server

!pass (new password, numbers only, must be 4-6 characters long) - Updates level password

!description (new description) - Updates level description

!public - makes the level public

!unlist - makes the level unlisted

!sharecp - Enables creator point sharing

!ldm - Enables LDM

!unldm - Disables LDM

Those are all the commands I know about. Hopefully this helps.

**Comment by UpriseDragon** [comment]
Thanks :) btw is there a command for unrating a level?

**Comment by AnubisTDG** [comment]
Just type _!rate NA 0_

**Comment by AnubisTDG** [comment]
You can also use the "req" button if your an admin to rate levels through the mod menu.

**Comment by UpriseDragon** [comment]
Thanks :)

**Comment by EndNation** [comment]
Is there a way to unverify the coins?

**Comment by CharMixGd** [comment]
A commad for rename levels : !rename [new name]
