### ISSUE TITLE
recents not showing and page is too

### ISSUE THREAD

**Issue by TiMuRL228** [Cvolton/GMDprivateServer#292]
On the page, the levels are not displayed, although they are + recents not showing
Page:
![image](https://user-images.githubusercontent.com/34861386/41149153-a69b86b0-6b2c-11e8-9f83-4cfb6b45d88e.png)

Recents:
![image](https://user-images.githubusercontent.com/34861386/41149179-b7ad3818-6b2c-11e8-9cab-3f7cb5810af1.png)

Please help
Thanks for help lol

**Comment by FrankOfficialGD** [comment]
i have that problem too

**Comment by xXFireBlastXx** [comment]
Maybe there is a level with an unknown rate, try to search from which page you can see the levels and search through IDs the problem level

**Comment by FrankOfficialGD** [comment]
xXFireBlastXx, what?? how?

**Comment by xXFireBlastXx** [comment]
See recent, try to find the page where it shows levels, being on that page, look for the most recent id of that page, since you found the most recent id of that page, try now to look for ids manually until you find the last level uploaded from the GDPS (Example, if my most recent id is 10 and the last id is 20, search from 10 to 20 the possible or possible levels with unknown rate)

It is difficult and confusing
