### ISSUE TITLE
Read the description

### ISSUE THREAD

**Issue by MarcGD130** [Cvolton/GMDprivateServer#432]
How do I make the mod rate only difficult / star and also how to make a rate delay like when someone rate a level it will have a delay effect

Ex:Rates a level > wait for 10 or 30 mins > the level gets rated wih star and ect...

**Comment by DarkGD123** [comment]
Hmm

**Comment by EMREOYUN** [comment]
GDPS is not supporting this, but this feature can be addable to code.

**Comment by Cvolton** [comment]
The delay is tricky because the server doesn't really have any way of running code in the background. A theoretical solution would be that a separate table would be made for levels to be rated and then the server would check and rate all remaining levels whenever someone makes a request for getGJLevels.
