### ISSUE TITLE
Can't search for levels

### ISSUE THREAD

**Issue by jeepercreepers9** [Cvolton/GMDprivateServer#450]
I can make an account, I can upload levels, but I can't search for them. The level appears on my database in phpMyAdmin, but I noticed that there were no added files in database/data/levels, if that helps.

**Comment by Cvolton** [comment]
This seems to be caused by multiple issues
1) the output of getGJLevels your GDPS returns is invalid, this results in the levels being unsearchable
2) your server does not have write permissions to data/levels. You can assign permissions (chmod 777) using any FTP client (such as FileZilla) if you're on a shared host
Please note that issue #1 may be caused by issue #2

**Comment by jeepercreepers9** [comment]
Using chmod 777 on the database folder worked, thank you so much!
