### ISSUE TITLE
how to add reupload level to my server? (levelReupload.php)

### ISSUE THREAD

**Issue by azmintech** [Cvolton/GMDprivateServer#651]
it works but cannot play... it says "something went wrong"
also the profile has no name and kinda green user help me pls

**Comment by azmintech** [comment]
but how? idk cs im new

**Comment by azmintech** [comment]
https://imgur.com/a/H9FdAS9

**Comment by Jecket22** [comment]
Not sure if that's the issue, but make sure that /database/data has all permissions (777) so that the levels can be downloaded by anyone. Also, you should make a new account for reuploaded levels and then copy the user-/ext-ID into levelReupload.php. If this is too confusing to you to set up, you can ask a friend (or me if you have nobody else to help) to set it up for you.

**Comment by azmintech** [comment]
ok thanks i did it
