### ISSUE TITLE
The level crashes after passing

### ISSUE THREAD

**Issue by System11X** [Cvolton/GMDprivateServer#958]
after passing the level, it crashes. this usually happens after I rate the level

**Comment by MegaSa1nt** [comment]
> after passing the level, it crashes. this usually happens after I rate the level

What "crash" means? It just quits from rated level? Dont rate short levels with difficulty above easy.

**Comment by System11X** [comment]
Yes, he just goes out of the level. Thanks for the answer, I'll try to experiment

**Comment by MegaSa1nt** [comment]
> Yes, he just goes out of the level. Thanks for the answer, I'll try to experiment

Its robtop anticheat system, so i dont recommend rating short levels

**Comment by KaliyaAlkaline** [comment]
To elaborate more, there's a specific anticheat system for rated levels. Anything above auto or easy must be at least Medium in length (about 40+ seconds), otherwise it will boot you out upon completion. This is to prevent people who use 10000x speed to instantly complete a level.

For insane levels and demon levels, you have to do at least 20 jumps or the level won't save properly to your account when you save/load data. I'm assuming this is also part of the anticheat.

**Comment by System11X** [comment]
Thank you all for the answers, yes, the anti-cheat system really works. Issue resolved, I'm closing it
